import { expect } from 'aegir/chai'
import Long from 'long'
import protobufjs from 'protobufjs'

function longifyBigInts (obj: any): any {
  const output = {
    ...obj
  }

  for (const key of Object.keys(output)) {
    const value = output[key]

    if (typeof value === 'bigint') {
      output[key] = Long.fromString(`${value.toString()}`)
    }

    if (Array.isArray(value)) {
      const v = []

      for (const val of value) {
        if (typeof val === 'bigint') {
          v.push(Long.fromString(`${val.toString()}`))
        } else {
          v.push(val)
        }
      }

      output[key] = v
    }
  }

  return output
}

function bigintifyLongs (obj: any): any {
  const output = {
    ...obj
  }

  for (const key of Object.keys(output)) {
    const value = output[key]

    if (Array.isArray(value)) {
      const v = []

      for (let i = 0; i < value.length; i++) {
        const val = value[i]

        if (val?.low != null && val?.high != null) {
          v.push(BigInt(new Long(val.low, val.high, val.unsigned).toString()))
        } else {
          v.push(val)
        }
      }

      output[key] = v
    } else if (value?.low != null && value?.high != null) {
      output[key] = BigInt(new Long(value.low, value.high, value.unsigned).toString())
    }
  }

  return output
}

function uint8ArrayifyBytes (obj: any): any {
  const output = {
    ...obj
  }

  for (const key of Object.keys(output)) {
    if (output[key] instanceof Uint8Array) {
      output[key] = Uint8Array.from(output[key])
    }
  }

  return output
}

function objectifyMaps (obj: any): any {
  const output = {
    ...obj
  }

  for (const key of Object.keys(output)) {
    if (output[key] instanceof Map) {
      const obj: Record<any, any> = {}
      const entries: MapIterator<[any, any]> = output[key].entries()

      for (const [key, value] of entries) {
        obj[key] = value
      }

      output[key] = obj
    }
  }

  return output
}

/**
 * Paper over differences between protons and protobuf.js output
 */
function normalizeProtonbufjs (obj: any, target: any): any {
  let output = bigintifyLongs(obj)
  output = uint8ArrayifyBytes(output)

  for (const key of Object.keys(output)) {
    // protobufjs sets unset message fields to `null`, protons does not set the field at all
    if (output[key] === null && target[key] == null) {
      delete output[key]
    }
  }

  for (const key of Object.keys(target)) {
    // protobufjs uses plain objects instead of maps
    if (target[key] instanceof Map) {
      output[key] = new Map(Object.entries(output[key] ?? {}))
    }
  }

  return output
}

export interface TestEncodingOptions {
  compareBytes?: boolean
  comparePbjs?: boolean
}

/**
 * Ensure:
 *
 * 1. the generated bytes between protons, pbjs and protobuf.js are the same
 * 2. protons and protobuf.js agree on deserialization
 */
export function testEncodings (obj: any, protons: any, proto: string, typeName: string, opts: TestEncodingOptions = {}): void {
  const protobufJsSchema = protobufjs.loadSync(proto).lookupType(typeName)
  const protobufJsBuf = protobufJsSchema.encode(protobufJsSchema.fromObject(objectifyMaps(longifyBigInts(obj)))).finish()

  const encoded = protons.encode(obj)

  if (opts.compareBytes !== false) {
    expect(encoded).to.equalBytes(Uint8Array.from(protobufJsBuf))
  }

  expect(protons.decode(encoded)).to.deep.equal(obj)
  expect(protons.decode(protobufJsBuf)).to.deep.equal(obj)

  expect(normalizeProtonbufjs(protobufJsSchema.toObject(protobufJsSchema.decode(encoded), {
    enums: String,
    defaults: true
  }), obj)).to.deep.equal(obj)
}
